### ISSUE TITLE
support ignoring failures

### ISSUE THREAD

**Issue by jannikmi** [tddschn/poetry-add-requirements.txt#3]
it would be nice to be able to ingore failures. This is useful since not all package requirements could be satisfiable.

something like:

`usage: poetry-add-requirements.txt [-h] [-D] [-I] [-V] [--ignore-errors] [requirements.txt files ...]`

**Comment by tddschn** [comment]
I updated the code and package on PyPI - could you try the installed version?

**Comment by jannikmi** [comment]
running ` poeareq --ignore-errors requirements.txt` works. thank you.
